---
title: "Text Mining - GameOfThrones"
author: "Jean-Paul Beaudry"
date: "`r format(Sys.time(), '%A %d %B, %Y')`"
output:
  html_document:
    highlight: textmate
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
options(repos=structure(c(CRAN="http://cran.r-project.org")))
options(repos="https://cran.rstudio.com" )
if (!require("tidyverse") | !require("DT")) {
  install.packages("tidyverse")
  install.packages("DT")
}
```

## Text Analytics

```{r echo=FALSE,eval=TRUE}
CONSUMER_KEY <- 'X'
CONSUMER_SECRET <- 'X'
access_token <- 'X'
access_secret <- 'X'
```

```{r echo=TRUE,eval=TRUE,display=TRUE,warning=FALSE, fig.height = 7,out.width = '100%'}
library("tidyverse")
library("twitteR")
library("tm")
library("ggplot2")
library("twitteR")
library("wordcloud")
library("RColorBrewer")
library("wordcloud")
library("plyr")
library("dplyr")
library("DT")
library("wordcloud2")
page.length=10

setup_twitter_oauth(CONSUMER_KEY, CONSUMER_SECRET, access_token, access_secret)
hashtag = "#GameOfThrones"
tweets <- twitteR::searchTwitter(hashtag, n=5000, lang="en")

tweets.df = ldply(tweets, function(t) t$toDataFrame())
head(tweets.df) %>%
  select(screenName, text) %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

file.csv <- stringr::str_replace_all(hashtag, "[^[:alnum:]]", "_")
file.csv <- stripWhitespace(file.csv)
write.csv(tweets.df, file = paste(file.csv,".csv ", sep=""))

nrow(tweets.df)

length(unique(tweets.df$screenName))

length(which(tweets.df$isRetweet))

length(which(tweets.df$retweeted))

mean(tweets.df$retweetCount, na.rm=TRUE)

tweets.df %>% 
  dplyr::group_by(screenName) %>% 
  dplyr::summarize(count = n()) %>%
  dplyr::arrange(desc(count)) %>%
  head(10) %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

tweets.df %>% 
  dplyr::group_by(screenName) %>% 
  dplyr::summarize(count = n()) %>%
  dplyr::arrange(desc(count)) %>%
  head(1) %>%
  datatable(style = 'bootstrap')

retweets.df <- tweets.df %>%
  dplyr::filter(retweetCount > 5)

retweets.df %>%
  select(screenName, text) %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

my.stopwords <- c(stopwords("english"),"rt", "amp","didn","tar")

tweets.df$text <- stringr::str_replace_all(tweets.df$text, "@\\w+"," ")
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "#\\S+"," ")## Remove Hashtags
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "http\\S+\\s*"," ")## Remove URLs
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "http[[:alnum:]]*"," ")## Remove URLs
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "http[[\\b+RT]]"," ")## Remove URLs
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "[[:cntrl:]]"," ")
tweets.df$text <- stringr::str_replace_all(tweets.df$text, hashtag," ")
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "[^[:alnum:]]", " ")
tweets.df$text <- removeWords(tweets.df$text, my.stopwords)
tweets.df$text <- stripWhitespace(tweets.df$text)
tweets.df$text <- stringr::str_replace_all(tweets.df$text, "[\U00010000-\U0010ffff]", "")
tweets.df$text <- gsub('[[:punct:] ]+',' ',tweets.df$text)
tweets.df$text <- gsub('[[:digit:] ]+',' ',tweets.df$text)
tweets.df$text <- sapply(tweets.df$text, function(x) tolower(x))

twt.corpus <- Corpus(VectorSource(tweets.df$text))

dtm <- DocumentTermMatrix(twt.corpus)
dtm

freq <- colSums(as.matrix(dtm))

freq.dt <- as.data.frame(freq)
freq.dt$term <- row.names(freq.dt)
row.names(freq.dt) <- 1:NROW(freq.dt)

freq.dt$term = removeWords(freq.dt$term, stopwords("english"))
freq.dt <- freq.dt[!freq.dt$term == "",]

freq.mean <- mean(freq.dt$freq); freq.mean

over.mean <- freq.dt[freq.dt$freq > freq.mean,] 

over.mean %>%
  arrange(term) %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

over.mean %>%
  arrange(desc(freq)) %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

over.mean %>%
  arrange(desc(freq)) %>%
  head(20) %>%
  mutate(term = reorder(term, freq)) %>%
  ggplot(aes(term, freq)) + 
  geom_col(show.legend = TRUE) +
  labs(x=NULL, y="Frequency") +
  coord_flip()+
  ggtitle("Most frequent terms")

wordcloud(freq.dt$term, freq.dt$freq, scale=c(3,0.5), 
          max.words=100, random.order=FALSE, 
          rot.per=0.10, use.r.layout=TRUE, 
          colors=brewer.pal(6, "Dark2")) 

top100 <- over.mean %>%arrange(desc(freq)) %>% head(100)
row.names(top100) <- top100$term
colnames(top100) <- c("freq","word")
top100 <- top100 %>% select(word, everything())
wordcloud2(top100)

top.words <- freq.dt %>% arrange(desc(freq)) %>% head(5); top.words

tdm <- TermDocumentMatrix(twt.corpus); tdm

assocs <- findAssocs(tdm, top.words$term, 0.3)

assocs.list <- lapply(assocs, function(x) data.frame(rhs = names(x), cor = x, stringsAsFactors = F))

assocs.df <- dplyr::bind_rows(assocs.list, .id = "lhs")

assocs.df  %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

assocs.df %>% 
  group_by(lhs) %>% 
  top_n(15, cor) %>%
  ungroup() %>%
  mutate(rhs = reorder(rhs, cor)) %>%
  ggplot(aes(rhs, cor, fill=lhs)) +
  geom_col(show.legend = F) +
  coord_flip() +
  facet_wrap(~lhs,ncol=2, scales="free") +
  ggtitle("Top five words and their correlation.") +
  labs(x=NULL, y="Correlation")

encodeSource <- function(x) {
  if(x=="<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>"){
    gsub("<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>", "iphone", x,fixed=TRUE)
  }else if(x=="<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>"){
    gsub("<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>","ipad",x,fixed=TRUE)
  }else if(x=="<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>"){
    gsub("<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>","android",x,fixed=TRUE)
  } else if(x=="<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>"){
    gsub("<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>","Web",x,fixed=TRUE)
  } else if(x=="<a href=\"http://www.twitter.com\" rel=\"nofollow\">Twitter for Windows Phone</a>"){
    gsub("<a href=\"http://www.twitter.com\" rel=\"nofollow\">Twitter for Windows Phone</a>","windows phone",x,fixed=TRUE)
  }else if(x=="<a href=\"http://dlvr.it\" rel=\"nofollow\">dlvr.it</a>"){
    gsub("<a href=\"http://dlvr.it\" rel=\"nofollow\">dlvr.it</a>","dlvr.it",x,fixed=TRUE)
  }else if(x=="<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>"){
    gsub("<a href=\"http://ifttt.com\" rel=\"nofollow\">IFTTT</a>","ifttt",x,fixed=TRUE)
  }else if(x=="<a href=\"http://earthquaketrack.com\" rel=\"nofollow\">EarthquakeTrack.com</a>"){
    gsub("<a href=\"http://earthquaketrack.com\" rel=\"nofollow\">EarthquakeTrack.com</a>","earthquaketrack",x,fixed=TRUE)
  }else if(x=="<a href=\"http://www.didyoufeel.it/\" rel=\"nofollow\">Did You Feel It</a>"){
    gsub("<a href=\"http://www.didyoufeel.it/\" rel=\"nofollow\">Did You Feel It</a>","did_you_feel_it",x,fixed=TRUE)
  }else if(x=="<a href=\"http://www.mobeezio.com/apps/earthquake\" rel=\"nofollow\">Earthquake Mobile</a>"){
    gsub("<a href=\"http://www.mobeezio.com/apps/earthquake\" rel=\"nofollow\">Earthquake Mobile</a>","earthquake_mobile",x,fixed=TRUE)
  }else if(x=="<a href=\"http://www.facebook.com/twitter\" rel=\"nofollow\">Facebook</a>"){
    gsub("<a href=\"http://www.facebook.com/twitter\" rel=\"nofollow\">Facebook</a>","facebook",x,fixed=TRUE)
  }else {
    "others"
  }
}

tweets.df$tweetSource = sapply(tweets.df$statusSource, 
                               function(sourceSystem) encodeSource(sourceSystem))

ggplot(tweets.df[tweets.df$tweetSource != 'others',], aes(tweetSource)) + 
  geom_bar(fill = "aquamarine4") + 
  theme(legend.position="none", 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Number of tweets") 

top.word <- freq.dt %>% arrange(desc(freq)) %>% head(1); top.word

results <- tweets.df %>% 
  filter(str_detect(text, top.word$term)) %>% 
  mutate(term = top.word$term, user = screenName) %>%
  select(term, screenName, text)

results %>%
  datatable(style = 'bootstrap', options = list(pageLength=page.length))

```

<a href="#top">Back to top</a>